### ISSUE TITLE
Hive port number for PyHive connection.

### ISSUE THREAD

**Issue by sealneaward** [frrmack/hadoop-tutorial#1]
Hi. I've followed your tutorial, and it is great and I have completed it with no real issues. I was looking to expand this a bit to include some PyHive code to do queries inside of Python.

The PyHive library has a connection object that requires a port to connect to.

```python
from pyhive import hive
conn = hive.Connection(host="localhost", port=10000, username="hduser")
```

The default port for Hive is 10000 right?

**Comment by frrmack** [comment]
Hi Neil. I'm glad it helped.

That sounds great. I've never used PyHive (coincidentally, it's been a while since I used Hive with _any_ interface). But it's exciting that there is a python library for that.

The default port should be 10000 indeed, as far as I know, but since I've never set a PyHive connection like this on a cluster I set up as described in this tutorial, I can't 100% confirm this will work -- but let me know if it does.
